### ISSUE TITLE
[FEATURE] Ignore issues & PRs that belong to a project (any)

### ISSUE THREAD

**Issue by C0ZEN** [Sonia-corporation/stale#165]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChristofferDahlen** [comment]
I would love to have this feature.

I currently want to avoid labeling any issues on my backlog board as stale.

Ps. Great job on this action!

**Comment by ChristofferDahlen** [comment]
Wow! @C0ZEN  Thanks for the quick implementation!
