### ISSUE TITLE
[FEATURE] Include only issues/prs on certain (allowlisted) projects

### ISSUE THREAD

**Issue by iainlane** [Sonia-corporation/stale#412]
**Is your feature request related to a problem? Please describe.**

We have a sort-of monorepo in our organisation. A few teams manage their issues through it, and attach these to cards on their team's projects. We'd like to be able to introduce a stale type workflow as _opt in_ across teams. With the current featureset in `sonia-corporation/stale` it would have to be all or nothing across the repo.

**Describe the solution you'd like**

When using `sonia-corporation/stable`, there would be a configuration option to specify an allowlist of projects to consider, something like:

  - `issue-include-only-projects: [none, team-a]`

and then only issues on either no project, or team a's board. Team b's would _not_ be staled.

Would this kind of feature be acceptable?

**Comment by C0ZEN** [comment]
@iainlane maybe this other [opened ticket](https://github.com/Sonia-corporation/stale/issues/312) is what you are looking for.
With such feature, you would be able to use the stale action only WHEN a specific card is associated to either the issue or the pull request, based on your configuration.
Note that you could have also multiple cron-jobs configured, which would use different configurations for different project cards.

If you confirm that this is what you need, I could prioritize https://github.com/Sonia-corporation/stale/issues/312 and expect a delivery within the current week.

**Comment by iainlane** [comment]
@C0ZEN sounds great, yes - feel free to mark this one as a dupe. Multiple cronjobs would work well I think.

The only thing we might have to worry about is the number of API requests maybe? Perhaps we could run them sequentially somehow and share state between runs..? Not sure if that'll be a real issue.

**Comment by iainlane** [comment]
Just to check, by project _card_ (per #312), we would be able to filter on _project_, right? The URL is something like https://github.com/orgs/ORG/projects/NNNN and I was imagining putting NNNN into the `stale.yml`

:-)

**Comment by C0ZEN** [comment]
> Just to check, by project _card_ (per #312), we would be able to filter on _project_, right? The URL is something like [github.com/orgs/ORG/projects/NNNN](https://github.com/orgs/ORG/projects/NNNN) and I was imagining putting NNNN into the `stale.yml`
> 
> :-)

The input is called “project-card” because GitHub is using this wording to refer to a project which is linked to an item in its API.
And indeed, in that case, the name of the project is used to find whether the associated projects should be processed or not, and this correct to assume NNNN is your example.

Anyhow, once the feature is released, do not hesitate to use the [dry-run option](https://sonia-corporation.github.io/stale/docs/dry-run-input) to play it safe on the first run, making sure that it's working, based on the logs, on your expectations.

**Comment by C0ZEN** [comment]
Note: duplicated of #312.

**Comment by C0ZEN** [comment]
@iainlane you can test the new option.
See the [new input](https://sonia-corporation.github.io/stale/docs/issues/inputs/issue-only-any-project-cards-input) and [an example](https://sonia-corporation.github.io/stale/docs/examples/multiple-cron-example).

**Comment by iainlane** [comment]
> @iainlane you can test the new option. See the [new input](https://sonia-corporation.github.io/stale/docs/issues/inputs/issue-only-any-project-cards-input) and [an example](https://sonia-corporation.github.io/stale/docs/examples/multiple-cron-example).

I will do next week!
